# Tox21 Activity Profiler


This interactive application allows users to browse activity profiles from the Tox21 dataset.  The activities of chemicals (based on CASRN) are presented. 

For a summary of data processing, see [this summary](https://www.dropbox.com/s/3s2k6258x377hid/pipeline_summary2.pdf?dl=0). The curves are available for browsing in a related application, the [Tox21 curve browser](/sandbox/tox21-curve-visualization/).

Disclaimer:

Although all reasonable efforts have been made to ensure the accuracy and reliability of the data, caution should be exercised when interpreting the results as artifacts are possible from nonspecific effects such as assay signal interference. The curve fitting and activity calls presented here are based on the Curvep pipeline [Hsieh J-H et al., JBC, 2015](http://journals.sagepub.com/doi/abs/10.1177/1087057115581317). Alternative analysis methods and interpretations of the data are available at NCATS (https://tripod.nih.gov/tox21/) and EPA (https://www.epa.gov/chemical-research/toxcast-dashboard)

## Quick start

Paste the following data-table into the "CAS & Cluster" text-box.

<table class='table table-condensed table-striped'>
<thead>
<tr>
  <th>CAS</th>
  <th>Cluster</th>
</tr>
</thead>
<tbody><tr>
  <td>83-79-4</td>
  <td>positive_zfish</td>
</tr>
<tr>
  <td>80-05-7</td>
  <td>negative_zfish</td>
</tr>
</tbody>
</table>

**Note**: paste the data AND the header column

***


### Required inputs

One of the two inputs below are required.

#### CAS & Cluster

A tab-delimited dataset (with header included). Two columns are allowed: chemicals and cluster. The cluster column is optional.

1. create one column (column name: CAS) or two columns of data (column names: CAS and Cluster) in Excel
  - CAS, chemical ID: one type is allowed, **CAS**
      - CAS: Chemical Abstracts Service registration ID, e.g., 83-79-4. Please put at least two CASRNs.
  - Cluster, chemical annotation: any annotation associated with the chemical that could be compared with the in vitro qHTS data
2. column names are case sensitive: **CAS** and **Cluster**
3. copy and paste to the text area

4. exclude activity from chemicals with suboptimal QC grade: (default ON), any chemicals with F, Fns, Fc QC grade will be removed. 

#### Data matrix

Alternatively, a data-matrix file can be uploaded.

1. the downloaded activity data can be modified and re-uploaded (e.g., add results from other external assays)
2. the file names have to contain **nwauc.logit|npod|nac50**. So it will recognize the type of activity and use the respective coloring scheme.
3. other data matrix with **CAS** as ID and comparable activity information can be uploaded (Note: non-Tox21 chemicals (defined by CAS) will be excluded).
4. **Cluster** information is optional.
5. **input_Chemical.Name** can be used to change the column names in the heatmap (optional).

**Notes:**
- _Activity limiting_ and _Enrichment Analysis_ function become invalid.
- _Assay filtering_ function is still functional.

#### Activity type

* Profiling: Select from one of two profiling types:
  - signal: results observation, e.g., whether the compound causes increasing or decreasing signal
    + **signal type**: currently only wauc is available, suitable for compound grouping
  - activity: Results interpretation, e.g., whether the compound is active
    + An activity type can also be specified
    + **activity type**
      * wauc: overall effect of the chemical
      * pod: point-of-departure (depending on noise level in the assay)
      * ac50: half-maximal effect concentration

<table class='table table-condensed table-striped'>
<thead>
<tr>
  <th>Type</th>
  <th>Value range</th>
  <th>Value description</th>
</tr>
</thead>
<tbody><tr>
  <td>wauc</td>
  <td>0 ~ 1</td>
  <td>higher value -&gt; higher activity <br> 0 -&gt; inactive <br> 1E-4 -&gt; inconclusive</td>
</tr>
<tr>
  <td>pod</td>
  <td>log10(M)*(-1)</td>
  <td>higher value -&gt; more potent <br> 1E-4 -&gt; inconclusive <br> 0 -&gt; inactive</td>
</tr>
</tbody>
</table>

ac50 type is same as pod type.

***
### Other settings

#### Limit activities
The default activity results are based on Curvep-wAUC pipeline. Activities from known assay interferences are flagged and labeled as **inconclusive**. 

* wAUC threshold: see above, only activity > threshold will be considered as active
* Emax threshold: half-maximal effect concentration (e.g., 30% relative to the positive control), only activity > threshold will be considered as active
* POD threshold: (uM), only activity more potent than the threshold will be considered as active
* EC50 threshold: (uM), only activity more potent than the threshold will be considered as active
* wAUC fold change (vs cytotoxicity): if > 1, the threshold is applied on both agonist and antagonist type calls
* exclude activity (antagonist-type calls) due to cytotoxicity: (default ON), the default setting in pipeline (see summary file)
* exclude activity with observed cytotoxicity: (default OFF)
* exclude activity due to auto-fluorescencent: (default ON)
* exclude activity with no reporter gene activity readout support: (default ON)
* exclude activity with suboptimal NCATS fits: (default OFF)
* exclude activity varied a lot between sources: (default OFF), the included activities can still be recognized in the heatmap by the # sign


***

#### Filter calls

Please see the __Call description__ tab to get complete call information

Simple regular expression rules:

1. get all specific calls
    + put _\^tox21_ in the text box `+ invert your selection = _OFF_
2. get agonist-type & specific calls
    + put _\^tox21.*-agonist_ in the text box `+ invert your selection = _OFF_

***

#### Sort chemicals
The columns of the heatmap can be ordered in three methods:

1. structure similarity
    + Tanimoto coefficient based on Leadscope proprietary structural fingerprints
    + hierarchical clustering with average linkage
    + chemicals are grouped by cutoff 0.7
    + a new parameter is created, chemClust, where chemClust = 0, are the compounds that cannot form clusters or compounds without structures

2. activity similarity
    + Euclidean distance based on respective activities
    + hierarchical clustering with average linkage

3. toxicity score (only for __activity__)
    + sum of the activities (unbounded, dependent on # of assays used)
        + wauc: sum of wauc values
        + pod or ac50: sum of wauc-weighted pod or ac50 values (in data matrix input, sum of pod/ac50 values instead)

***

### Formatting & outputs

1. make inconclusive as inactive: (default ON), it makes all inconclusive (value = 1E-4) as inactives (value = 0)
2. show chemical similarity dendrogram: (default OFF), the clustered dendrogram will replace the the heatmap
3. keep heatmap size one page: (default OFF)
4. show(download) activity data with flags: (default OFF), assay interferece information could be appended
4. adjust font size when downloading heatmap or online

  * Download Activities(CAS)
  * Download Activities (Tox21ID)
  * Save Heatmap
  * Download Enrichment Analysis

***

### Tabs

#### Input chemicals

If the input chemicals are not available, they will not have _GSID_.
Current information is based on EPA DSSTOX.

#### Profile

The heatmap will be displayed here.

##### Main map

* columns are chemicals
* rows are calls
* cells are activities
* coloring scheme: please refer the color bar
* gray color: not tested. However if "make inconclusive as inactive" OFF, it could also mean _inconclusive_.

##### annotation map

* columns are chemicals
* first row is toxScore (only available in __activity__)
* second row is userClust (__Cluster__)
* third row is chemCust

#### Potency plot

Only shown for pod or ec50 as activity.

#### Activity data(CAS)

background data used for heatmap and potency plot

#### Activity data(Tox21ID)

The background data before collapsing based on CAS

#### Enrichment analysis

* DAVID (more stringent) Fisher's exact test is applied
* n: number of compounds in a class; n\_p: number of actives in a class; N\_P: number of actives in the population;n: number of compounds in the population


#### Call description

call information

### Troubleshooting

* Error: 'breaks' are not unique. It is possible that the input compounds are not active in any of the assays. Please add another compound (e.g. 80-05-7).
* The compound is missing on the heatmap. The compound may not be tested or none of its sources passes the chemical QC.
* Error: non-numeric matrix extent. >1 call and >1 chemical are needed to form a heatmap


***

### Release notes

*v1.1*

* initial public release

*v1.2*

* new: enrichment panel is added; results can be downloaded
* changed: purity information fixed(v5a5) v030716
* changed: add PubChem AIDs for the lately released assays in PubChem
* changed: default was set to activity clustering (columns)
* changed: structural clustering fixed for missing Tox21 chemicals due to low purity

*v1.3*
* new: allow duplicate CAS if Cluster information is different
* new: add Tox21AgencyID/Tox21ID background data (Tox21AgencyID)
* new: add CAS data without filtering by QC grade
* new: allow to retrieve back activities due to autofluorescence and ch2 issue
* new: add wAUC fold change filter
* new: add flag information for the CAS data
* fixed: no observed cytotoxicity function
* changed: purity information updated (201608, v5a7)
* changed: call description updated (80 calls, v2)

***

### Contact

For further information, contact:

Jui-Hua Hsieh, Ph.D.
[Biomolecular Screening Branch](http://www.niehs.nih.gov/research/atniehs/labs/bmsb/toxico/staff/hsieh/index.cfm)
